version: "3.9"
#Triggering a PR build.
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: hr-curve-nginx:latest
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - web
    healthcheck:
      test: ["CMD-SHELL", "service nginx status"]
      timeout: 10s
    logging:
      options:
        max-size: 10m
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: hr-curve:latest
    ports:
      - "${WEB_PORT_INTERNAL}:${WEB_PORT_INTERNAL}"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python manage.py check"]
      timeout: 15s
    logging:
      options:
        max-size: 10m
