services:
  nginx:
    build:
      dockerfile: Dockerfile.nginx
    container_name: nginx
    depends_on: [ web ]
    environment:
      BACKEND_URL: http://web
    ports:
      - "3001:3001"
    restart: unless-stopped
    logging:
      options:
        max-size: 10m

  web:
    build:
      dockerfile: Dockerfile.app
    container_name: web
    environment:
      WEB_PORT_INTERNAL: 3000
      GUNICORN_WORKERS: 2
      GUNICORN_LOG_LEVEL: debug
      GUNICORN_LIMIT_REQ_LINE: 4094
      GUNICORN_LIMIT_REQ_FIELDSIZE: 8190
      GUNICORN_TIMEOUT: 30
    ports:
      - "3000:3000"
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
