version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8003"
    volumes:
      - .:/app
      - ./staticfiles:/static
    ports:
      - "${WEB_PORT_INTERNAL}:${WEB_PORT_INTERNAL}"
    env_file:
      - .env
    restart: on-failure
