version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: hr-curve-nginx:latest
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - web
    logging:
      options:
        max-size: 10m
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: hr-curve:latest
    ports:
      - "${WEB_PORT_INTERNAL}:${WEB_PORT_INTERNAL}"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
