[tool.poetry]
name = "frontend"
version = "1.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
django = "^4.1.7"
scikit-learn = "^1.2.2"
scipy = "^1.10.1"
pypdf2 = "^3.0.1"
pandas = "^1.5.3"
lmfit = "^1.1.0"
xhtml2pdf = "^0.2.9"
matplotlib = "^3.7.1"
gunicorn = "^20.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
