[tool.poetry]
name = "frontend"
version = "1.0.0"
description = ""
authors = [
    "Tobias Mueller <to.mueller@gmail.com",
    "Tyler De Jong <TDeJong@nhcweb.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
django = "^5.0.0"
scikit-learn = "^1.2.2"
scipy = "^1.10.1"
pandas = "^2.2"
lmfit = "^1.1.0"
xhtml2pdf = "^0.2.9"
matplotlib = "^3.7.1"
gunicorn = "^20.1.0"
pip = "^23.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
