# Generated by Django 4.0 on 2023-01-16 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RatingCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('datetime', models.DateField()),
                ('stage', models.FloatField()),
                ('discharge', models.FloatField()),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rctool.user')),
            ],
        ),
    ]
