{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $secretKey:= .Values.global.secrets.secretKey | default (randAlphaNum 32) }}
{{- $secretName := printf "%s" .Release.Name }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName ) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
  # set below to existing secret data or generate a random one when not exists
{{- $secretKey = (get $secretData "SECRET_KEY") | default ($secretKey | b64enc) }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rctool
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  SECRET_KEY: {{ $secretKey | quote }}
{{- end }}

