name: Build And Deploy Docker Image to Openshift Dev

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  secret-search:
    name: Secret Search
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: secret-search
        uses: Hacks4Snacks/secret-search@v1.1
        with:
          exclude-file: docker-compose.yml
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [ frontend ]
        include:
          - package: frontend
            triggers: ('*')

    steps:
      - uses: actions/checkout@v3
      - uses: bcgov-nr/action-builder-ghcr@v0.0.2
        with:
          package: ${{ matrix.package }}
          tag: latest
          tag_fallback: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ${{ matrix.triggers }}


  deploys:
    name: Deploy
    needs:
      - build
    # If any of the previous created a build, then deploy
    if: contains(needs.*.outputs.build, 'true')
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [ frontend ]
        include:
         -  name: frontend
            file: .github/openshift/openshift.deploy.yml
            overwrite: true

    steps:
      - uses: bcgov-nr/action-deployer-openshift@v0.1.0
        with:
          environment: dev
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          penetration_test: false
