name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/*"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: test-prod
  cancel-in-progress: false

jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        id: pr
        uses: bcgov-nr/action-get-pr@v0.0.1

  deploys-test:
    name: TEST Deployments
    needs: [vars]
    environment: test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [frontend, rctool]
        include:
          - name: frontend
            file: frontend/openshift.nginx.deploy.yml
          - name: rctool
            file: frontend/openshift.deploy.yml
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v2.1.0
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: true
          parameters:
            -p ZONE=test -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:${{ needs.vars.outputs.pr }}
