name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/*"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: test-prod
  cancel-in-progress: false
      
permissions:
  packages: write
  contents: read

jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr }}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        id: pr
        uses: bcgov/actions/get-pr@bf09757562da93a1825abba5290d87f3811d9f5b # get-pr

  deploy-test:
    name: Deploy (TEST)
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      environment: test
      params: --set global.autoscaling=true --set rctool.pdb.enabled=true --set frontend.pdb.enabled=true --set-string frontend.gunicorn.logLevel=debug

  promote-test:
    name: Promote Images
    needs: [deploy-test, vars]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [frontend, rctool]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@e6aaef25c595b6e0edd18bf4c7dbfea3abd43299 # v5
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          tags: test
          target: ${{ needs.vars.outputs.pr }}

