name: PR Closed

on:
  pull_request:
    types: [closed]

permissions: {}

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  cleanup:
    name: Cleanup and Images
    # Skip cleanup for fork PRs targeting upstream where repository secrets are stripped
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      packages: write
    uses: bcgov/actions-openshift/.github/workflows/.pr-close.yml@75454b2b33edf37135f6f167775c77a3414207f6 # v0.3.1
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      cleanup: helm
      packages: frontend rctool
