name: Pull Request

on:
  pull_request:

permissions:
  contents: read

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [frontend, rctool]
        include:
          - package: frontend
            build_file: ./frontend/Dockerfile.nginx
          - package: rctool
            build_file: ./frontend/Dockerfile.app
    steps:
      - uses: bcgov/action-builder-ghcr@1a3767a04ade69edf7e4857c44269d1100282581 # v4.1.0
        with:
          package: ${{ matrix.package }}
          build_file: ${{ matrix.build_file }}
          build_context: ./frontend
          tag_fallback: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ('frontend/')

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      triggers: ('frontend/' 'charts/' '.github/workflows/.deployer.yml')
      params: --set global.secrets.persist=false --set-string frontend.gunicorn.logLevel=debug

  results:
    name: PR Results
    needs: [builds, deploys]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
