name: Pull Request

on:
  pull_request:

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [frontend, rctool]
        include:
          - package: frontend
            build_file: ./frontend/Dockerfile.nginx
          - package: rctool
            build_file: ./frontend/Dockerfile.app
    steps:
      - uses: actions/checkout@v4
      - uses: bcgov/action-builder-ghcr@v2.3.0
        with:
          package: ${{ matrix.package }}
          build_file: ${{ matrix.build_file }}
          build_context: ./frontend
          tag: ${{ github.event.number }}
          tag_fallback: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ('frontend/')

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys
    needs: [ builds ]
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.deployer.yml@v0.9.0
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      triggers: ('frontend/' 'charts/')
      params: --set global.secrets.persist=false --set-string frontend.gunicorn.logLevel=debug
      oc_server: ${{ vars.OC_SERVER }}


  results:
    name: PR Results
    needs: [builds, deploys]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
