name: Pull Request

on:
  pull_request:

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [frontend, rctool]
        include:
          - package: frontend
            build_file: ./frontend/Dockerfile.nginx
          - package: rctool
            build_file: ./frontend/Dockerfile.app
    steps:
      - uses: actions/checkout@v4
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          package: ${{ matrix.package }}
          build_file: ${{ matrix.build_file }}
          build_context: ./frontend
          tag: ${{ github.event.number }}
          tag_fallback: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ('frontend/')

  deploys:
    name: Deploys
    needs: [builds]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [frontend, rctool]
        include:
          - name: frontend
            file: frontend/openshift.nginx.deploy.yml
          - name: rctool
            file: frontend/openshift.deploy.yml
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v3.0.1
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: true
          parameters:
            -p ZONE=${{ github.event.number }}
            -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:${{ github.event.number }}

  results:
    name: PR Results
    needs: [builds, deploys]
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - if: contains(needs.*.result, 'failure')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
