name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true
  
jobs:
  validate:
    name: Validate PR
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@0b8121a528aaa05ef8def2f79be9081691dfe98a # v0.9.0
    with:
      markdown_links: |
        - [Frontend](https://${{ github.event.repository.name }}-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca/) available

  results:
    name: Validate Results
    needs: [validate]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Workflow completed successfully!"
