name: PROD Release

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploys:
    name: PROD Deployments
    environment: prod
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [frontend, rctool]
        include:
          - name: frontend
            file: frontend/openshift.nginx.deploy.yml
          - name: rctool
            file: frontend/openshift.deploy.yml
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v2.1.0
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: true
          parameters:
            -p ZONE=test -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:latest

  image-promotions:
    name: Promote Images
    needs: [deploys]
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [frontend, rctool]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          tags: prod
          target: latest
