name: PROD Release

on:
  release:
    types: [published]

concurrency:
  group: test-prod
  cancel-in-progress: false

jobs:
  deploys:
    name: Deploy (PROD)
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.deployer.yml@v0.8.3
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      environment: prod
      tag: test
      params: --set global.autoscaling=true --set rctool.pdb.enabled=true --set frontend.pdb.enabled=true

  promotions:
    name: Promote Images
    needs: [deploys]
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [frontend, rctool]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          tags: prod
          target: test
