name: Scheduled

on:
  schedule: [cron: "0 11 * * 6"] # 3 AM PST = 12 PM UDT, Saturdays
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  zap_scan:
    runs-on: ubuntu-24.04
    name: Penetration Tests
    permissions:
      security-events: write
    env:
      URL: ${{ github.event.repository.name }}-test-frontend.apps.silver.devops.gov.bc.ca
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@75ee1686750ab1511a73b26b77a2aedd295053ed # v0.12.0
        with:
          allow_issue_writing: true
          artifact_name: "zap_rctool"
          cmd_options: "-a"
          issue_title: "ZAP: rctool"
          target: https://${{ env.URL }}
